import {Carousel,Card} from '@/components/ui/specials-linear-carousel';
import React from 'react';
import {createRoot} from 'react-dom/client';
import {CoverFlowCarousel,type CarouselItem} from '@/components/ui/3-d-coverflow-carousel';
declare global {interface Window{cmsCarouselPoems?:CarouselItem[]}}
const fallback='/assets/carousel-placeholder.svg';
function mountFromGrid(selector:string,label:string){const grid=document.querySelector<HTMLElement>(selector);if(!grid)return;const mount=document.createElement('div');mount.className='carousel-mount';const toggle=document.createElement('button');toggle.type='button';toggle.className='btn carousel-view-toggle';toggle.textContent='Switch to list view';toggle.setAttribute('aria-pressed','true');grid.before(toggle,mount);grid.classList.add('carousel-source-hidden');const root=createRoot(mount);let key='';
 function refresh(){const cards=[...grid!.children].filter(c=>c instanceof HTMLElement&&!c.hidden&&!c.classList.contains('is-filtered-out')) as HTMLElement[];const items:CarouselItem[]=cards.map(c=>{const isProject=c.classList.contains('project-card');const action=isProject?(c.querySelector<HTMLAnchorElement>('a[href*="case-studies"],a[href^="/project/"]')||c.querySelector<HTMLAnchorElement>('.project-links a')):c.querySelector<HTMLAnchorElement>('.cert-actions a');return {titleLine1:c.querySelector('h3')?.textContent||'Untitled',tag:isProject?c.querySelector('.project-meta')?.textContent||'Project':c.querySelector('.cert-kind')?.textContent||'Certificate',desc:isProject?c.querySelector('.muted')?.textContent||'':c.querySelector('.cert-issuer')?.textContent||'',img:c.querySelector('img')?.getAttribute('src')||fallback,ctaUrl:action?.getAttribute('href')||(isProject?'/project/'+c.id:'#'),ctaText:isProject?'Explore project':'View certificate'};});const next=JSON.stringify(items);if(next!==key){key=next;root.render(label==='Certificates'?<Carousel items={items.map((item,index)=><Card key={item.ctaUrl+item.titleLine1} index={index} card={{src:item.img,title:item.titleLine1,category:item.tag,content:<p>{item.desc}</p>,href:item.ctaUrl}}/> )}/>:<CoverFlowCarousel items={items} sectionLabel={label}/>);}}
 toggle.onclick=()=>{const carousel=Boolean(mount.hidden);mount.hidden=!carousel;grid.classList.toggle('carousel-source-hidden',carousel);toggle.textContent=carousel?'Switch to list view':label==='Certificates'?'Switch to carousel view':'Switch to 3D view';toggle.setAttribute('aria-pressed',String(carousel));};refresh();new MutationObserver(refresh).observe(grid,{subtree:true,attributes:true,attributeFilter:['hidden','class'],childList:true});}
mountFromGrid('.project-grid','Projects');mountFromGrid('.certificate-grid','Certificates');
const cover=document.querySelector<HTMLElement>('.poetry-cover');if(cover&&window.cmsCarouselPoems?.length){const mount=document.createElement('div');mount.className='carousel-mount';cover.replaceWith(mount);createRoot(mount).render(<CoverFlowCarousel items={window.cmsCarouselPoems} sectionLabel="Poetry"/>);}
