const $=id=>document.getElementById(id);let rows=[],schema={},current=null,dirty=false,busy=false;
const selects={category:{projects:{'data-ml':'Data & ML','software-iot':'Software & IoT'},certificates:{data:'Data & analytics',ai:'AI & cloud',systems:'Security & systems',creative:'Creative',business:'Business',activities:'Activities'}},group:{tech:'Tech',uem:'UEM',iitm:'IITM',atl:'ATL'},language:{en:'English',bn:'Bengali'},format:{video:'Video (MP4)',image:'Image',text:'Written poem'}};
const labels={title:'Title',category:'Category',lead:'Short introduction',description:'Description',tags:'Skills / tags (separate with commas)',image:'Preview image',link:'Repository / external link',caseText:'Project overview',issuer:'Issuer / organizer',kind:'Record type (award, participation, completion…)',group:'Certificate group',file:'Original file',language:'Language',format:'Poem format',text:'Text',roles:'Roles (space-separated: data business software)',evidence:'Supporting evidence'};
function status(s,error=false){$('adminStatus').textContent=s;$('adminStatus').dataset.error=error;}
async function api(path,options){const r=await fetch('/api/admin/'+path,options);const d=await r.json();if(!r.ok){if(r.status===403)$('signin').hidden=false;throw Error(d.error||'Request failed');}return d;}
function abandon(){return !dirty||confirm('Discard your unsaved changes?');}
function list(){const kind=$('collection').value;const q=$('find').value.toLowerCase();$('add').hidden=kind==='pages';$('items').replaceChildren();for(const r of rows.filter(r=>r.kind===kind&&r.data.title.toLowerCase().includes(q))){const b=document.createElement('button');b.className='admin-item';b.type='button';b.setAttribute('aria-pressed',String(current?.id===r.id));b.append(document.createTextNode(r.data.title));const meta=document.createElement('span');meta.textContent=(r.hidden?'Hidden · ':'Visible · ')+'Order '+r.position;b.append(meta);b.onclick=()=>{if(!busy&&abandon())edit(r);};$('items').append(b);}}
function edit(r){current=structuredClone(r);dirty=false;$('editor').hidden=false;$('editorEmpty').hidden=true;$('editorTitle').textContent=r.revision===0&&!rows.some(x=>x.id===r.id)?'Add item':'Edit '+r.data.title;$('fields').replaceChildren();for(const name of schema[r.kind]){const label=document.createElement('label');label.textContent=labels[name]||name;let options=name==='category'?selects.category[r.kind]:selects[name];let field=document.createElement(options?'select':['description','caseText','text','evidence'].includes(name)?'textarea':'input');field.name=name;field.id='field-'+name;if(options)for(const [val,text]of Object.entries(options)){const o=document.createElement('option');o.value=val;o.textContent=text;field.append(o);}field.value=r.data[name]|| (options?Object.keys(options)[0]:'');if(name==='title')field.required=true;field.addEventListener('input',()=>dirty=true);label.append(field);
if(['file','image'].includes(name)){const upload=document.createElement('input');upload.type='file';upload.accept=name==='image'?'image/png,image/jpeg,image/webp':'.png,.jpg,.jpeg,.webp,.pdf,.mp4';upload.setAttribute('aria-label','Upload '+labels[name]);upload.onchange=async()=>{const f=upload.files[0];if(!f)return;if(f.size>20*1024*1024){status('Please choose a file smaller than 20 MB.',true);return;}busy=true;$('save').disabled=true;status('Uploading '+f.name+'…');try{const d=await api('upload',{method:'POST',headers:{'Content-Type':f.type},body:f});field.value=d.url;dirty=true;status('Uploaded. Save changes to use this file on your website.');}catch(e){status(e.message,true);}finally{busy=false;$('save').disabled=false;}};label.append(upload);const hint=document.createElement('small');hint.textContent=name==='image'?'Optional. Upload a preview or paste an HTTPS image URL.':'Upload a file or paste its HTTPS URL. Maximum 20 MB.';label.append(hint);}$('fields').append(label);}$('position').value=r.position;$('hiddenItem').checked=r.hidden;list();}
async function load(){const d=await api('content');rows=d.records;schema=d.fields;$('adminApp').hidden=false;list();}
$('collection').onchange=()=>{if(busy||!abandon()){$('collection').value=current?.kind||'projects';return;}current=null;dirty=false;$('editor').hidden=true;$('editorEmpty').hidden=false;list();};$('find').oninput=list;$('add').onclick=()=>{if(!busy&&abandon())edit({id:crypto.randomUUID(),kind:$('collection').value,data:{},position:rows.filter(r=>r.kind===$('collection').value).length,hidden:false,revision:0});};$('position').oninput=$('hiddenItem').onchange=()=>dirty=true;
$('cancel').onclick=()=>{if(!busy&&abandon()){const old=rows.find(r=>r.id===current.id);if(old)edit(old);else{$('editor').hidden=true;current=null;dirty=false;}}};
$('editor').onsubmit=async e=>{e.preventDefault();if(busy)return;const data=Object.fromEntries(new FormData(e.target));busy=true;$('save').disabled=true;status('Saving…');try{await api('save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...current,data,position:Number($('position').value),hidden:$('hiddenItem').checked})});const id=current.id;dirty=false;await load();edit(rows.find(r=>r.id===id));status('Saved. Your website now reflects these changes.');}catch(e){status(e.message,true);}finally{busy=false;$('save').disabled=false;}};
$('backup').onclick=()=>{const blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-content-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});load().then(()=>status('Choose a collection to begin.')).catch(e=>status(e.message,true));
