import seed from './seed.json';
import templates from './templates.json';
import { createRemoteJWKSet, jwtVerify } from 'jose';
const htmlResponse=html=>new Response(html,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'}});
const OWNER_EMAIL='saptarshi2005.kgp@gmail.com';
const kinds=['projects','certificates','poems','photography','skills','pages'];
const fields={projects:['title','category','lead','description','tags','image','link','demo','caseText'],certificates:['title','issuer','kind','group','category','file','image'],poems:['title','language','format','file','image','text'],photography:['title','description','image'],skills:['title','description','tags','roles','evidence'],pages:['title','text']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=(d,status=200)=>new Response(JSON.stringify(d),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function url(s){if(!s)return '';if(/^https:\/\/[a-z0-9.-]+(?::443)?(?:[/?#]|$)/i.test(s))return s;if(/^(?:assets|certificates|poems|case-studies)\/[a-zA-Z0-9_./%-]+$/.test(s)&&!s.includes('..'))return '/'+s;if(/^\/media\/[a-zA-Z0-9-]+$/.test(s))return s;return '';}
const demoDefaults={project_606:'https://mediassist-chatbot-saptarshi.onrender.com/',project_707:'https://ai-hr-2.vercel.app/',project_1111:'https://ai-hr-rho-ten.vercel.app/'};
const demoUrl=r=>url(r.data.demo)||demoDefaults[r.id]||'';
async function records(env){const q=await env.DB.prepare('SELECT * FROM content').all();const map=new Map(seed.map(r=>[r.id,{...r,data:{...r.data}}]));for(const r of q.results)map.set(r.id,{...r,hidden:!!r.hidden,data:JSON.parse(r.data)});return [...map.values()].sort((a,b)=>a.position-b.position||a.id.localeCompare(b.id));}
const accessKeys=new Map();
async function isOwner(req,env){let id,email,key='admin';if(env.POLICY_AUD||env.TEAM_DOMAIN){if(!env.POLICY_AUD||!env.TEAM_DOMAIN)return false;const issuer=env.TEAM_DOMAIN.replace(/\/$/,'');if(!/^https:\/\/[a-z0-9.-]+\.cloudflareaccess\.com$/i.test(issuer))return false;const token=req.headers.get('cf-access-jwt-assertion');if(!token)return false;try{if(!accessKeys.has(issuer))accessKeys.set(issuer,createRemoteJWKSet(new URL(issuer+'/cdn-cgi/access/certs')));const verified=await jwtVerify(token,accessKeys.get(issuer),{issuer,audience:env.POLICY_AUD});id=verified.payload.sub;email=verified.payload.email?.toLowerCase();key='admin_cloudflare';}catch{return false;}}else{if(new URL(req.url).hostname!=='iamsapta.saptarshi2005-kgp.chatgpt.site')return false;id=req.headers.get('oai-authenticated-user-id');email=req.headers.get('oai-authenticated-user-email')?.toLowerCase();}if(!id||email!==OWNER_EMAIL)return false;const pinned=await env.DB.prepare('SELECT user_id FROM owner WHERE key = ?').bind(key).first();if(pinned)return pinned.user_id===id;await env.DB.prepare('INSERT OR IGNORE INTO owner (key,user_id) VALUES (?,?)').bind(key,id).run();return (await env.DB.prepare('SELECT user_id FROM owner WHERE key = ?').bind(key).first()).user_id===id;}
const tags=s=>String(s||'').split(',').filter(Boolean).map(t=>`<span class="tag">${esc(t.trim())}</span>`).join('');
function render(r){const d=r.data;const demo=r.kind==='projects'?demoUrl(r):'';if(d.html){if(demo&&!d.html.includes(demo))return d.html.replace('</article>',`<div class="project-links"><a href="${esc(demo)}" target="_blank" rel="noopener noreferrer">Try live app ↗</a></div></article>`);return d.html;}const title=esc(d.title);const img=url(d.image);const file=url(d.file);const link=url(d.link);switch(r.kind){
case 'projects':return `<article class="card project-card" id="${r.id}" data-category="${esc(d.category)}" data-reveal>${img?`<a class="project-preview" href="/project/${r.id}"><img src="${esc(img)}" loading="lazy" alt="${title}"></a>`:''}<div class="project-meta">${esc(d.category)}</div><h3>${title}</h3><p class="project-lead">${esc(d.lead)}</p><p class="muted">${esc(d.description)}</p><div class="tag-list">${tags(d.tags)}</div><div class="card-actions"><a class="btn" href="/project/${r.id}">Project overview →</a><button class="btn-details" data-project="${r.id}" aria-haspopup="dialog">Quick details →</button></div>${demo||link?`<div class="project-links">${demo?`<a href="${esc(demo)}" target="_blank" rel="noopener noreferrer">Try live app ↗</a>`:''}${link?`<a href="${esc(link)}" target="_blank" rel="noopener noreferrer">View repository ↗</a>`:''}</div>`:''}</article>`;
case 'certificates':return `<article class="certificate-card" data-cert-group="${esc(d.group)}" data-cert-category="${esc(d.category)}">${img?`<a class="cert-preview" href="${esc(file)}" target="_blank" rel="noopener"><img src="${esc(img)}" alt="${title}" loading="lazy"></a>`:''}<div class="cert-body"><span class="cert-kind">${esc(d.kind)}</span><h3>${title}</h3><p class="cert-issuer">${esc(d.issuer)}</p><div class="cert-actions"><a href="${esc(file)}" target="_blank" rel="noopener">View certificate ↗</a><a href="${esc(file)}" download>Download ↓</a></div></div></article>`;
case 'skills':return `<article class="card skill-card" data-skill-roles="${esc(d.roles)}"><h3>${title}</h3><p class="muted">${esc(d.description)}</p><div class="tag-list">${tags(d.tags)}</div><details class="skill-evidence"><summary>Explore the evidence</summary><p>${esc(d.evidence)}</p></details></article>`;
case 'poems':return `<article class="poem-card" id="${r.id}" data-language="${esc(d.language)}">${d.format==='text'?`<p class="poem-text">${esc(d.text)}</p>`:`<div class="poem-media">${d.format==='video'?`<video controls playsinline preload="none" poster="${esc(img)}" aria-label="${title}"><source src="${esc(file)}" type="video/mp4"></video>`:`<a href="${esc(file)}" target="_blank" rel="noopener"><img src="${esc(file)}" alt="${title}" loading="lazy"></a>`}</div>`}<div class="poem-info"><span class="eyebrow">${d.language==='bn'?'বাংলা':'ENGLISH'}</span><h2>${title}</h2>${file?`<a class="text-link" href="${esc(file)}" target="_blank" rel="noopener">Open original ↗</a>`:''}</div></article>`;
case 'photography':return `<figure class="photo-card">${img?`<a href="${esc(img)}" target="_blank" rel="noopener"><img src="${esc(img)}" alt="${title}" loading="lazy" decoding="async"></a>`:''}<figcaption><span>${title}</span>${d.description?`<p>${esc(d.description)}</p>`:''}</figcaption></figure>`;
}return '';}
function shell(title,body){return new Response(`<!doctype html><html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Saptarshi Mandal</title><link rel="stylesheet" href="/styles.css"></head><body><main class="wrap case-page"><a class="btn" href="/#projects">← Portfolio</a>${body}</main></body></html>`,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'}});}
export default {async fetch(req,env){try{let path=new URL(req.url).pathname;if(path.startsWith('/case-studies/')&&!path.endsWith('.html'))path+='.html';
if(path.startsWith('/api/admin/')||path==='/admin'||path==='/admin.html'){
 if(!await isOwner(req,env)){if(path.startsWith('/api/'))return json({error:'Owner sign-in required'},403);return shell('Owner access',env.POLICY_AUD?'<h1>Portfolio admin</h1><p>Sign in through the configured Cloudflare Access application to manage this portfolio.</p>':'<h1>Portfolio admin</h1><p>Sign in with the owner’s ChatGPT account to manage this portfolio.</p><a class="btn" target="_top" href="/signin-with-chatgpt?return_to=%2Fadmin">Sign in with ChatGPT</a>');}
 if(!['GET','HEAD'].includes(req.method)&&req.headers.get('Origin')!==new URL(req.url).origin)return json({error:'Invalid request origin'},403);
 if(path==='/api/admin/content'&&req.method==='GET')return json({records:await records(env),fields});
 if(path==='/api/admin/save'&&req.method==='POST'){
 if(Number(req.headers.get('Content-Length')||0)>150000)return json({error:'Entry too large'},413);
 const input=await req.json();if(!input||typeof input!=='object'||!kinds.includes(input.kind)||!/^[-a-zA-Z0-9_]{1,100}$/.test(input.id))return json({error:'Invalid item'},400);
 const all=await records(env),old=all.find(r=>r.id===input.id);if(old&&old.kind!==input.kind)return json({error:'Item type cannot change'},400);if(input.kind==='pages'&&!old)return json({error:'Use an existing page section'},400);
 const data={};for(const f of fields[input.kind]){data[f]=String(input.data?.[f]||'').trim();if(data[f].length>20000)return json({error:'Text is too long'},400);if(['link','demo','image','file'].includes(f)&&data[f]&&!url(data[f]))return json({error:'Use an uploaded file or an HTTPS link'},400);}
 if(!data.title)return json({error:'Title is required'},400);
 const choices={group:['tech','uem','iitm','atl'],language:['en','bn'],format:['image','video','text']};for(const [k,allowed]of Object.entries(choices))if(k in data&&!allowed.includes(data[k]))return json({error:'Invalid '+k},400);
 if(input.kind==='certificates'&&!data.file)return json({error:'Upload or link a certificate'},400);if(input.kind==='poems'&&data.format!=='text'&&!data.file)return json({error:'Upload or link a poem'},400);
 if(input.kind==='projects'&&!['data-ml','software-iot'].includes(data.category))return json({error:'Choose a project category'},400);
 if(input.kind==='pages')data.selector=old.data.selector;
 if(old && fields[input.kind].every(f=>String(old.data[f]||'').trim()===data[f]) && old.data.html)data.html=old.data.html;
 const rev=Number(input.revision)||0;const pos=Math.min(100000,Math.max(0,Number(input.position)||0));const sql='INSERT INTO content (id,kind,data,position,hidden,revision,updated) VALUES (?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,position=excluded.position,hidden=excluded.hidden,revision=content.revision+1,updated=excluded.updated WHERE content.revision = ?';
 const result=await env.DB.prepare(sql).bind(input.id,input.kind,JSON.stringify(data),pos,input.hidden?1:0,new Date().toISOString(),rev).run();if(!result.meta.changes)return json({error:'This item changed in another tab. Reload before saving.'},409);return json({ok:true});}
 if(path==='/api/admin/upload'&&req.method==='POST'){
 const size=Number(req.headers.get('Content-Length'));if(!size||size>20*1024*1024)return json({error:'Choose a file smaller than 20 MB'},413);const f=await req.blob();const type=f.type.split(';')[0];if(!['image/png','image/jpeg','image/webp','application/pdf','video/mp4'].includes(type))return json({error:'Use PNG, JPG, WebP, PDF or MP4'},400);const bytes=new Uint8Array(await f.slice(0,16).arrayBuffer());const sig=Array.from(bytes);const valid=type==='application/pdf'?String.fromCharCode(...bytes.slice(0,5))==='%PDF-':type==='image/png'?sig.slice(0,4).join(',')==='137,80,78,71':type==='image/jpeg'?sig[0]===255&&sig[1]===216:type==='image/webp'?String.fromCharCode(...bytes.slice(8,12))==='WEBP':String.fromCharCode(...bytes.slice(4,8))==='ftyp';if(!valid)return json({error:'File content does not match its format'},400);
 const id=crypto.randomUUID();await env.BUCKET.put(id,f.stream(),{httpMetadata:{contentType:type}});await env.DB.prepare('INSERT INTO uploads (id,name,type,size) VALUES (?,?,?,?)').bind(id,'upload',type,f.size).run();return json({url:'/media/'+id});}
 if(path==='/admin'||path==='/admin.html')return htmlResponse(templates.admin);return json({error:'Not found'},404);
}
if(path.startsWith('/media/')){const key=path.slice(7);if(!/^[a-f0-9-]{36}$/.test(key))return new Response('Not found',{status:404});if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405,headers:{Allow:'GET, HEAD'}});const o=await env.BUCKET.get(key,{range:req.headers});if(!o)return new Response('Not found',{status:404});const h=new Headers();o.writeHttpMetadata(h);h.set('X-Content-Type-Options','nosniff');h.set('Cache-Control','public,max-age=86400');h.set('Accept-Ranges','bytes');if(req.headers.has('Range')&&o.range){h.set('Content-Range',`bytes ${o.range.offset}-${o.range.offset+o.range.length-1}/${o.size}`);h.set('Content-Length',String(o.range.length));}return new Response(req.method==='HEAD'?null:o.body,{status:req.headers.has('Range')&&o.range?206:200,headers:h});}
if(['/','/index.html','/poetry.html','/poetry'].includes(path)||path.startsWith('/project/')||path.startsWith('/case-studies/')){
const all=await records(env);const visible=all.filter(r=>!r.hidden);const projects=visible.filter(r=>r.kind==='projects');
if(path.startsWith('/project/')||path.startsWith('/case-studies/')){const r=projects.find(r=>'/project/'+r.id===path||'/'+r.data.caseUrl===path||seed.find(s=>s.id===r.id)?.data.caseUrl===path.slice(1));if(!r)return new Response('Project not found',{status:404});if(r.revision===0&&path.startsWith('/case-studies/')&&templates.cases[path])return htmlResponse(templates.cases[path]);return shell(r.data.title,`<h1>${esc(r.data.title)}</h1><p>${esc(r.data.lead)}</p>${url(r.data.image)?`<figure class="case-figure"><img src="${esc(url(r.data.image))}" alt="${esc(r.data.title)}"></figure>`:''}<p>${esc(r.data.description)}</p><div class="poem-text">${esc(r.data.caseText)}</div>${demoUrl(r)?`<a class="btn" href="${esc(demoUrl(r))}" target="_blank" rel="noopener noreferrer">Try live app ↗</a>`:''}${url(r.data.link)?`<a class="btn" href="${esc(url(r.data.link))}" target="_blank" rel="noopener noreferrer">View repository ↗</a>`:''}`);}
let response=htmlResponse(path.startsWith('/poetry')?templates.poetry:templates.home);let rw=new HTMLRewriter();const groups={projects:'.project-grid',certificates:'.certificate-grid',skills:'#skillsGrid',poems:'.poem-grid',photography:'.photography-grid'};
for(const [kind,selector]of Object.entries(groups))rw=rw.on(selector,{element(el){const items=visible.filter(r=>r.kind===kind);if(items.length||kind!=='photography')el.setInnerContent(items.map(render).join(''),{html:true});}});
for(const r of all.filter(r=>r.kind==='pages'&&r.revision>0))rw=rw.on(r.data.selector,{element(el){el.setInnerContent(r.hidden?'':esc(r.data.text).replace(/\n/g,'<br>'),{html:true});}});
const pd=Object.fromEntries(projects.map(r=>[r.id,{title:r.data.title,category:r.data.category,lead:r.data.lead,desc:r.data.description,tags:r.data.tags.split(',').map(s=>s.trim()),link:url(r.data.link)||'/project/'+r.id,linkLabel:url(r.data.link)?'View repository':'Project overview'}]));const poemItems=visible.filter(r=>r.kind==='poems').map(r=>({titleLine1:r.data.title,tag:r.data.language==='bn'?'বাংলা':'English',img:url(r.data.image)||'/assets/carousel-placeholder.svg',ctaUrl:'/poetry.html#'+r.id,ctaText:'Read / watch poem'}));rw=rw.on('head',{element(el){el.prepend('<script>window.cmsCarouselPoems='+JSON.stringify(poemItems).replace(/</g,'\\u003c')+';window.cmsProjectData='+JSON.stringify(pd).replace(/</g,'\\u003c')+';</script>',{html:true});}});
for(const g of ['tech','uem','iitm','atl'])rw=rw.on(`[data-cert-group-filter="${g}"]`,{element(el){el.setInnerContent((g==='tech'?'Tech':g.toUpperCase())+' ('+visible.filter(r=>r.kind==='certificates'&&r.data.group===g).length+')');}});
rw=rw.on('.poem-features',{element(el){el.setInnerContent(visible.filter(r=>r.kind==='poems').slice(0,3).map(r=>`<a href="/poetry.html#${r.id}">${esc(r.data.title)}</a>`).join(''),{html:true});}}).on('.poetry-cover-bottom',{element(el){el.setInnerContent(visible.filter(r=>r.kind==='poems').length+' poems · Explore →');}}).on('.poetry-collection>.poetry-deck',{element(el){el.setInnerContent('Explore the poetry collection in its original visual form. Visible videos loop silently. Hover to pause; move away to resume. Reduced-motion preferences are respected.');}}).on('#poemStatus',{element(el){el.setInnerContent(visible.filter(r=>r.kind==='poems').length+' poems');}});
response=rw.transform(response);const h=new Headers(response.headers);h.set('Cache-Control','no-store');return new Response(response.body,{status:response.status,headers:h});}
return env.ASSETS.fetch(req);
}catch(e){console.error('Portfolio request failed',e.message);return json({error:'Content is temporarily unavailable. Please try again; your saved work is preserved.'},503);}}};
